import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.util.List;
import java.util.Map;

/**
 * Part 05, Lesson 06 — Null Safety
 *
 * DON'T EDIT THIS FILE. It is the pristine copy you can always reset from.
 *
 * Start by duplicating it:
 *     cp Exercise.java Solution.java
 *
 * Then write your answers in Solution.java, deleting each `throw` as you go.
 * See README.md for how to run the tests.
 *
 * The class below is called `Solution`, not `Exercise`, on purpose. Java only
 * forces a *public* type to match its filename, so a package-private class may
 * live in a file of any name. That is what lets `cp` be the entire setup step:
 * your copy is `Solution.java` holding `class Solution`, which is exactly what
 * the compiler wants, and no renaming is needed.
 */
class Solution {

    /**
     * A nullability marker, PROVIDED — nothing to implement here.
     *
     * Every @Nullable you have ever seen is a declaration about this size. It
     * has runtime retention so `isMarkedNullable` below can read it back, which
     * is more than most of them bother with.
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.METHOD)
    @interface Nullable {
    }

    /** PROVIDED — a record with two components, used to provoke an NPE. */
    record Contact(String name, String email) {
    }

    /**
     * Reject null at the door, naming what was missing.
     *
     *   required("jane@example.com", "email")  -> "jane@example.com"
     *   required(null, "email")                -> NullPointerException
     *                                             getMessage() == "email must not be null"
     *
     * Use `java.util.Objects.requireNonNull(value, message)`. It RETURNS its
     * argument, which is the whole reason it is shaped that way:
     *
     *     this.email = required(email, "email");
     *
     * — the check and the assignment are one expression, so there is no way to
     * write the assignment and forget the check.
     */
    static <T> T required(T value, String name) {
        throw new UnsupportedOperationException("required: not implemented");
    }

    /**
     * Provoke a NullPointerException by calling `length()` on a contact's name,
     * and report what the JVM said about it.
     *
     *   npeMessage(new Contact("Jane", "j@x.com"))  -> "ok"
     *   npeMessage(new Contact(null, "j@x.com"))
     *       -> "Cannot invoke \"String.length()\" because the return value of
     *           \"Solution$Contact.name()\" is null"
     *
     * Write `contact.name().length()` inside a try, catch NullPointerException,
     * and return `e.getMessage()`. Return "ok" when nothing was thrown.
     *
     * That message is generated by the JVM at throw time, on by default since
     * Java 15. Read its two halves: what you tried to call, and which
     * expression was null.
     */
    static String npeMessage(Contact contact) {
        throw new UnsupportedOperationException("npeMessage: not implemented");
    }

    /**
     * An order that cannot be constructed wrong and cannot be corrupted after.
     *
     *   var input = new ArrayList<>(List.of("a", "b"));
     *   var order = new Order("Jane", input);
     *   input.add("c");
     *   order.items()          -> ["a", "b"]     (unaffected)
     *   order.items().add("d") -> UnsupportedOperationException
     *
     *   new Order(null, input)        -> NPE, "customer must not be null"
     *   new Order("Jane", null)       -> NPE, "items must not be null"
     *   new Order("Jane", [a, null])  -> NullPointerException
     *
     * Two defences, both needed. Check the references at the top of the
     * constructor, before any field is assigned — a half-built object that
     * escaped is worse than no object. Then take a copy, because a caller that
     * keeps a reference to the list they passed can otherwise edit your state
     * from outside.
     *
     * `List.copyOf` does the copy, returns something unmodifiable, and rejects
     * null elements, all in one call. `new ArrayList<>(items)` does none of
     * those three.
     */
    static final class Order {
        Order(String customer, List<String> items) {
            throw new UnsupportedOperationException("Order: not implemented");
        }

        /** The customer, never null: the constructor refused to build without one. */
        String customer() {
            throw new UnsupportedOperationException("customer: not implemented");
        }

        /** The items, safe to hand out: nothing a caller does can change them. */
        List<String> items() {
            throw new UnsupportedOperationException("items: not implemented");
        }
    }

    /**
     * Find out, by trying it, what nulls a map will accept.
     *
     *   nullTolerance(new HashMap<>())            -> "both"
     *   nullTolerance(new ConcurrentHashMap<>())  -> "neither"
     *   nullTolerance(new TreeMap<>())            -> "value only"
     *
     * Answer with exactly one of "both", "key only", "value only", "neither".
     * Probe with `map.put(null, "v")` and `map.put("k", null)`, catching
     * NullPointerException around each. The map is written to, so callers pass
     * a throwaway.
     *
     * There is no interface method for this and no way to ask a map in advance
     * — which is the point. `Map` does not say, so every implementation gets to
     * differ, and one of the most-used ones differs from the others.
     */
    static String nullTolerance(Map<String, String> map) {
        throw new UnsupportedOperationException("nullTolerance: not implemented");
    }

    /**
     * Read a count, treating a missing key as zero.
     *
     *   countOf(Map.of("a", 3), "a")  -> 3
     *   countOf(Map.of("a", 3), "b")  -> 0
     *   countOf(Map.of(), "a")        -> 0
     *
     * The naive version — `int n = counts.get(key);` — throws a
     * NullPointerException from a line containing no visible dereference, and
     * that is the trap the README names. `Map` has a method that avoids it.
     */
    static int countOf(Map<String, Integer> counts, String key) {
        throw new UnsupportedOperationException("countOf: not implemented");
    }

    /**
     * Normalise a possibly-null list into one that is safe to iterate.
     *
     *   safeList(null)              -> []
     *   safeList(List.of("a","b"))  -> ["a", "b"], unmodifiable
     *   safeList([a, null])         -> throws NullPointerException
     *
     * Never return null from a method whose type is a collection: an empty
     * collection already means "nothing", and it needs no check at the call
     * site. Rejecting a null element rather than storing it is the same
     * argument one level down.
     */
    static List<String> safeList(List<String> maybeNull) {
        throw new UnsupportedOperationException("safeList: not implemented");
    }

    /**
     * A method that genuinely can return null, and says so with the annotation
     * declared at the top of this file.
     *
     *   maybeName(true)   -> "Jane"
     *   maybeName(false)  -> null
     *
     * Annotate it `@Nullable`. Then read the tests and notice what the
     * annotation did NOT do.
     */
    static String maybeName(boolean present) {
        throw new UnsupportedOperationException("maybeName: not implemented");
    }

    /**
     * Is the named method of this class annotated `@Nullable`?
     *
     *   isMarkedNullable("maybeName")  -> true
     *   isMarkedNullable("required")   -> false
     *   isMarkedNullable("nonesuch")   -> false
     *
     * Search `Solution.class.getDeclaredMethods()` by name — the parameter
     * types differ, so looking one up by signature is more trouble than it is
     * worth here. `Method.isAnnotationPresent(Class)` does the check.
     */
    static boolean isMarkedNullable(String methodName) {
        throw new UnsupportedOperationException("isMarkedNullable: not implemented");
    }
}
