import java.util.ArrayList;
import java.util.List;

/**
 * A place for the other support classes to record that they were initialised.
 * Provided for you; you do not edit this file.
 *
 * The log has to live somewhere that is ALREADY initialised, or reading it
 * would be the very event you are trying to observe.
 */
public final class InitLog {

    private static final List<String> ENTRIES = new ArrayList<>();

    private InitLog() {
    }

    /** Records an entry and hands it straight back, so it can sit in a field initialiser. */
    public static String record(String entry) {
        ENTRIES.add(entry);
        return entry;
    }

    /** A copy of everything recorded so far, in order. */
    public static List<String> snapshot() {
        return List.copyOf(ENTRIES);
    }
}
