/**
 * A fixture for the reflection lesson. You do not edit this file — it is the
 * "user class" your mapper has to make sense of, and everything in it is
 * private on purpose.
 *
 * It is annotated with the @Column you declare in Solution.java, so until that
 * annotation exists this file will not compile.
 */
class Customer {

    static int created;

    @Column(value = "customer_id", id = true)
    private final int id;

    @Column("full_name")
    private final String name;

    @Column
    private final int age;

    private final String scratch = "never persisted";

    private Customer(int id, String name, int age) {
        this.id = id;
        this.name = name;
        this.age = age;
        created++;
    }

    static Customer of(int id, String name, int age) {
        return new Customer(id, name, age);
    }

    private String initials() {
        StringBuilder out = new StringBuilder();
        for (String part : name.split(" ")) {
            if (!part.isEmpty()) out.append(part.charAt(0)).append('.');
        }
        return out.toString();
    }

    private String repeat(String text, int times) {
        return text.repeat(times);
    }

    private void explode() {
        throw new IllegalStateException("nope");
    }

    @Override
    public String toString() {
        return "Customer[" + id + "]";
    }
}
