import java.util.List;

/**
 * One entry of a classpath — a directory or a jar — and the binary names of
 * the classes it provides. Provided for you; you do not edit this file.
 *
 * A classpath is a `List<ClasspathEntry>`, and the order is the search order.
 */
public record ClasspathEntry(String name, List<String> classNames) {

    public ClasspathEntry {
        classNames = List.copyOf(classNames);
    }

    public boolean provides(String binaryName) {
        return classNames.contains(binaryName);
    }

    @Override
    public String toString() {
        return name;
    }
}
