/**
 * One field at each of Java's four access levels, so that reflection has
 * something real to report. Provided for you; you do not edit this file.
 *
 * Note that `packagePrivate` carries no keyword at all. That is the point:
 * package-private is what you get by not choosing.
 */
public class Visibility {

    public int openToAll;

    protected int forSubclassesAndPackage;

    int packagePrivate;

    private int mine;

    public int mine() {
        return mine;
    }
}
